version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - coolify
    labels:
      - "coolify.managed=true"
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`reactv2.signalstrading.app`)"
      - "traefik.http.services.app.loadbalancer.server.port=80"
      - "traefik.http.routers.app.entrypoints=web,websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"

networks:
  coolify:
    external: true