import '../styles/globals.css'
import { Inter } from 'next/font/google'
import { ThemeProvider } from "next-themes"
import { cn } from "@/lib/utils"
import DashboardLayout from "@/components/layouts/DashboardLayout"
import MobileNav from "@/components/MobileNav"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        inter.variable
      )}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <DashboardLayout>
            <main className="md:pl-64 pb-16 md:pb-0">
              {children}
            </main>
            <MobileNav />
          </DashboardLayout>
        </ThemeProvider>
      </body>
    </html>
  )
}
